### ISSUE TITLE
Remove [[Construct]] and exoticness from wrapped async functions

### ISSUE THREAD

**Issue by littledan** [tc39/proposal-async-context#36]
I don't think the [[Construct]] behavior of `.wrap`'s output is particularly useful; I'd prefer we prioritize simplicity over copying everything that `.bind` does. Let's have `.wrap` output an ordinary function instead of some exotic object kind, again for simplicity. This can be done with [CreateBuiltinFunction](https://tc39.es/ecma262/#sec-createbuiltinfunction).

**Comment by legendecas** [comment]
This can be addressed in https://github.com/tc39/proposal-async-context/pull/55 as it removes the HOF with `AsyncSnapshot`. `AsyncSnapshot.prototype.run` and `AsyncLocal.prototype.run` merely call the given function.
