### ISSUE TITLE
Can we use this now?

### ISSUE THREAD

**Issue by hazae41** [tc39/proposal-async-context#58]
Does the provided code work? Can we start using this proposal as a NPM package? Thanks

**Comment by rezonant** [comment]
No, this is a proposal for including async context in Ecmascript itself, it's not an NPM package. There are existing solutions available for various cases in the mean time. See AsyncLocalStorage and related APIs in Node.js. In the browser it's not as good of a story-- Zone.js provides these mechanisms but it's context tracking cannot work over native promises right now.

**Comment by jridgewell** [comment]
Right, if you're in Node.js or similar server environment, you should use [AsyncLocalStorage](https://nodejs.org/api/async_context.html) for now. There's no suitable replacement in browsers.
